# Generated by Django 2.1.5 on 2019-04-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('classic', 'CLASSIC'), ('confirmed', 'CONFIRMED'), ('banned', 'BANNED')], max_length=16)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('discord_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('channel_logs', models.BigIntegerField(default=0)),
                ('channel_admin', models.BigIntegerField(default=0)),
                ('channel_request', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='rank',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server'),
        ),
    ]
