# Generated by Django 2.1.5 on 2019-04-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='name',
        ),
    ]
