# Generated by Django 2.1.5 on 2019-04-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20190406_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='moderator',
            new_name='moderators',
        ),
    ]
