# Generated by Django 2.1.5 on 2019-04-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_remove_server_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='channel_logs',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
