# Generated by Django 2.1.5 on 2019-04-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20190406_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='emails_domains',
            field=models.ManyToManyField(blank=True, to='servers.EmailDomain'),
        ),
    ]
