# Generated by Django 2.1.5 on 2019-04-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_channel_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='channel_admin',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='channel_request',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='server',
            name='channel_logs',
            field=models.BigIntegerField(default=0),
        ),
    ]
