# Generated by Django 2.1.5 on 2019-04-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20190408_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='icon_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
