# Generated by Django 2.1.5 on 2019-04-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_ranks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranks',
            old_name='cri_name',
            new_name='name',
        ),
    ]
