# Generated by Django 2.1.5 on 2019-04-04 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20190404_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('classic', 'CLASSIC'), ('rank_confirmed', 'RANK_CONFIRMED'), ('rank_banned', 'RANK_BANNED')], max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('discord_id', models.BigIntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
        migrations.RemoveField(
            model_name='ranks',
            name='server',
        ),
        migrations.DeleteModel(
            name='Ranks',
        ),
    ]
