# Generated by Django 2.1.5 on 2019-04-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_auto_20190404_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='server_id',
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
