# Generated by Django 2.1.3 on 2019-01-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=128)),
                ('login', models.CharField(max_length=128)),
            ],
        ),
    ]
