# Generated by Django 2.1.5 on 2019-04-04 15:12

from django.db import migrations, models
import website.apps.members.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hash', models.CharField(blank=True, default=website.apps.members.models.generate_hash, max_length=128)),
                ('login', models.CharField(blank=True, max_length=128)),
                ('servers', models.ManyToManyField(blank=True, to='servers.Server')),
            ],
        ),
    ]
