# Generated by Django 2.1.5 on 2019-04-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='login',
            new_name='email',
        ),
    ]
