# Generated by Django 2.1.5 on 2019-04-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hash',
            field=models.CharField(default='', max_length=128),
        ),
    ]
