# Generated by Django 2.1.5 on 2019-04-04 02:00

from django.db import migrations, models
import website.apps.members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='hash',
            field=models.CharField(blank=True, default=website.apps.members.models.generate_hash, max_length=128),
        ),
        migrations.AlterField(
            model_name='member',
            name='login',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
