# Generated by Django 2.1.5 on 2019-04-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20190404_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
    ]
