# Generated by Django 2.1.5 on 2019-04-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='icon_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
