# Generated by Django 2.1.5 on 2019-04-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_remove_server_members'),
        ('members', '0004_remove_member_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='members',
            field=models.ManyToManyField(blank=True, to='servers.Server'),
        ),
    ]
