# Generated by Django 2.1.5 on 2019-04-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='members',
            new_name='servers',
        ),
    ]
