# Generated by Django 2.1.5 on 2019-04-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('group', 'GROUP'), ('login', 'LOGIN'), ('user', 'USER')], max_length=64)),
                ('value', models.CharField(default='', max_length=64)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=128)),
                ('login', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('unban', 'UNBAN'), ('ban', 'BAN'), ('addgroup', 'ADDGROUP'), ('delgroup', 'DELGROUP'), ('certify', 'CERTIFY')], max_length=20)),
                ('ban_type', models.CharField(choices=[('group', 'GROUP'), ('login', 'LOGIN'), ('user', 'USER')], max_length=20)),
                ('login', models.CharField(default='', max_length=64)),
                ('value', models.CharField(default='', max_length=64)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
    ]
