# Generated by Django 2.1.3 on 2019-01-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=128)),
                ('login', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
