# Generated by Django 2.1.5 on 2019-04-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190408_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='type',
            field=models.CharField(choices=[('unban', 'UNBAN'), ('ban', 'BAN'), ('addgroup', 'ADDGROUP'), ('delgroup', 'DELGROUP'), ('certify', 'CERTIFY'), ('config', 'CONFIG')], max_length=20),
        ),
    ]
