# Generated by Django 2.1.3 on 2019-01-28 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
        ('groups', '0004_ban_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.Server'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='type',
            field=models.CharField(choices=[('group', 'GROUP'), ('login', 'LOGIN'), ('user', 'USER')], max_length=64),
        ),
    ]
