# Generated by Django 2.1.5 on 2019-04-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_update_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='author',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
