# Generated by Django 2.1.3 on 2019-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20190128_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('unban', 'UNBAN'), ('ban', 'BAN'), ('addgroup', 'ADDGROUP'), ('delgroup', 'DELGROUP')], max_length=20)),
                ('ban_type', models.CharField(choices=[('group', 'GROUP'), ('login', 'LOGIN'), ('user', 'USER')], max_length=20)),
                ('value', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
