# Generated by Django 2.1.3 on 2019-01-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_updates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='Update',
        ),
    ]
