# Generated by Django 2.1 on 2019-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_update_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='type',
            field=models.CharField(choices=[('unban', 'UNBAN'), ('ban', 'BAN'), ('addgroup', 'ADDGROUP'), ('delgroup', 'DELGROUP'), ('certify', 'CERTIFY')], max_length=20),
        ),
    ]
